#! /bin/sh
#
# unifi		This script loads unifi WIFI module
#

[ -e /usr/sbin/unififw ] || exit 0

case "$1" in
        start|"")
                if [ "$VERBOSE" != no ]
                then
                        echo -n "Loading unifi module... "
                fi

		modprobe unifi_sdio

                [ "$VERBOSE" != no ] && echo "done."
                ;;
        stop)
                [ "$VERBOSE" != no ] && echo "done."
                ;;
        *)
                echo "Usage: unifi {start|stop}" >&2
                exit 1
                ;;
esac

