#! /bin/sh
#
# System-V init script for the openntp daemon
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="network time protocol daemon"
NAME=ntpd
DAEMON=/usr/sbin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

case "$1" in
  start)
	if [ "$NTPD" = "yes" ] ; then
		echo -n "Starting $DESC: $NAME"
		start-stop-daemon -S -q -x $DAEMON -- -g
		echo "."
	fi
	;;
  stop) echo -n "Stopping $DESC: $NAME"
	start-stop-daemon -K -q -n $NAME
	echo "."
	;;
  reload|force-reload) 
	if [ "$NTPD" = "yes" ] ; then
		echo -n "Reloading $DESC configuration..."
		start-stop-daemon -K -q -n $NAME -s 1
		echo "done."
	fi
  ;;
  restart) 
	if [ "$NTPD" = "yes" ] ; then
		echo "Restarting $DESC: $NAME"
		$0 stop
		sleep 1
		$0 start
	fi
	;;
  *) echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
