#!/bin/sh

# /var could be ext4
fsck /target/var

mount -a

export HOME=/root

UPDATE_IMAGE=/target/var/lib/fwupdate/rootfs.ubifs.sign DELETE_IMAGE=1 TARGET=/target/rootfs UMOUNT_LIST="/target/var /proc /sys" FALLBACK="busybox init" exec /sbin/fwupdate update-recover

# fallback
echo 1 > /sys/class/leds/error/brightness

exec busybox init

