#!/bin/sh

set -e

# these environment variables are already set:
# BUILDROOT_CONFIG
# TARGET_DIR
# STAGING_DIR
# HOST_DIR
# BINARIES_DIR
# BASE_DIR

if [ -n "$BRAND" ]; then
	echo "Releasing for brand $BRAND"
	BRAND_POSTFIX="-$BRAND"
fi

if [ -n "$RELEASE" ]; then
	RELEASE_TAG=$(date +%Y%m%d)
	RELEASE_DIR=$BASE_DIR/releases/$RELEASE_TAG$BRAND_POSTFIX

	mkdir -p $RELEASE_DIR
	mkdir -p $TARGET_DIR/var/state

	echo $RELEASE_TAG >$TARGET_DIR/etc/release
	echo $RELEASE_TAG >$TARGET_DIR/var/state/previous-release

	make -C $BASE_DIR BR2_DEFCONFIG=$RELEASE_DIR/defconfig savedefconfig
else
	echo "NOT DOING RELEASE BUILD! (use make RELEASE=1 to make a release)"
	rm -f $TARGET_DIR/etc/release
	rm -f $TARGET_DIR/var/state/previous-release
fi

