#!/bin/sh

# script is called with an image directory as first argument

set -e

IMAGES_DIR=$1

# these environment variables are already set:
# BUILDROOT_CONFIG
# TARGET_DIR
# STAGING_DIR
# HOST_DIR
# BINARIES_DIR
# BASE_DIR

if [ -n "$RELEASE" ]; then
	RELEASE_TAG=$(date +%Y%m%d)
	RELEASE_DIR=$BASE_DIR/releases/$RELEASE_TAG

	mkdir -p $RELEASE_DIR/images

	cp $IMAGES_DIR/* $RELEASE_DIR/images/
else
	echo "NOT DOING RELEASE BUILD! (use make RELEASE=1 to make a release)"
fi

