#!/bin/sh
#
# Start the rtuadmin-renderer...
#

case "$1" in
  start)
 	echo "Starting rtuadmin-renderer..."
	/usr/bin/rtuadmin-renderer --no-restart
	;;
  stop)
	echo -n "Stopping rtuadmin-renderer..."
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

