#############################################################
#
# tripot
#
#############################################################
TRIPOT_VERSION = master
TRIPOT_SITE = ssh://merlin.swind.sk:29418/embedded-tools
TRIPOT_SITE_METHOD = git
TRIPOT_SUBDIR = tripot
TRIPOT_DEPENDENCIES = qt
TRIPOT_INSTALL_STAGING = NO
TRIPOT_INSTALL_TARGET = YES
TRIPOT_CONF_OPT += -DSERIAL_DEVICE1=/dev/${BR2_PACKAGE_TRIPOT_DEVICE1} -DSERIAL_DEVICE2=/dev/${BR2_PACKAGE_TRIPOT_DEVICE2} 

TRIPOT_RESOLUTION_$(BR2_PACKAGE_TRIPOT_RESOLUTION_320x240) += 320x240
TRIPOT_RESOLUTION_$(BR2_PACKAGE_TRIPOT_RESOLUTION_480x272) += 480x272
TRIPOT_RESOLUTION_$(BR2_PACKAGE_TRIPOT_RESOLUTION_640x480) += 640x480
TRIPOT_RESOLUTION_$(BR2_PACKAGE_TRIPOT_RESOLUTION_800x480) += 800x480

TRIPOT_CONF_OPT += -DDISPLAY_RESOLUTION=$(TRIPOT_RESOLUTION_y)

define TRIPOT_INITSCRIPT
	$(INSTALL) -D -m 0755 $(TRIPOT_SRCDIR)/initscript-tripot $(TARGET_DIR)/etc/init.d/S90tripot
endef

define TRIPOT_MARK_RESOLUTION
	rm -f $(TARGET_DIR)/etc/app-resolution-*
	$(INSTALL) -D -m 0755 /dev/null $(TARGET_DIR)/etc/app-resolution-$(TRIPOT_RESOLUTION_y)
endef

TRIPOT_POST_INSTALL_TARGET_HOOKS += TRIPOT_INITSCRIPT
TRIPOT_POST_INSTALL_TARGET_HOOKS += TRIPOT_MARK_RESOLUTION

$(eval $(call cmake-package))

