#!/bin/sh

set -e

BR=$(pwd)
MOD=$BR/board/tind/compact-rtu/mod-apollo

mkdir -p $TARGET_DIR/usr/share/webapps

# function modules
install -D -m 0755 $MOD/apollo.exe $TARGET_DIR/usr/share/opendaf/function-modules/apollo.exe
mkdir -p $TARGET_DIR/var/lib/opendaf/function-modules
ln -sf /usr/share/opendaf/function-modules/apollo.exe $TARGET_DIR/var/lib/opendaf/function-modules/apollo.exe

# index page
install -D -m 0644 $MOD/index.html $TARGET_DIR/usr/share/webapps/index/index.html
install -D -m 0644 $MOD/style.css $TARGET_DIR/usr/share/webapps/index/css/style.css

# apollo-ui
tar -C $TARGET_DIR/usr/share/webapps -xf $MOD/apollo-ui.tgz
cd $TARGET_DIR/var/www && ln -sf ../../usr/share/webapps/apollo-ui apollo-ui

# dafman database update
install -D -m 0755 $MOD/update-dafman $TARGET_DIR/usr/sbin/update-dafman
install -D -m 0644 $MOD/update-dafman.service $TARGET_DIR/etc/systemd/system/update-dafman.service
mkdir -p $TARGET_DIR/etc/systemd/system/multi-user.target.wants
ln -fs ../update-dafman.service $TARGET_DIR/etc/systemd/system/multi-user.target.wants/update-dafman.service

# mod upgrade script
install -D -m 0755 $MOD/upgrade $TARGET_DIR/usr/sbin/mod-upgrade

# KVDS on external storage
cat <<EOF >$TARGET_DIR/usr/libexec/cgi-bin/kvds-ext
#!/bin/sh

KVDS_ROOT=/srv/kvds exec /usr/bin/kvds cgi
EOF
chmod 755 $TARGET_DIR/usr/libexec/cgi-bin/kvds-ext

# lighttpd mod-specific configuration
cat <<EOF >$TARGET_DIR/etc/lighttpd/conf.d/mod.conf
url.rewrite-once += (
	"^/astroclock/(.*)" => "/cgi-bin/astro-op/\$1",
	"^/kvds-ext/(.*)" => "/cgi-bin/kvds-ext/\$1"
)
EOF

# astroclock configuration
cat <<EOF >$TARGET_DIR/etc/astroclock.conf
set -e
LATITUDE=\$(kvds get site.location.latitude)
LONGITUDE=\$(kvds get site.location.longitude)
EOF

# astroclock runtime service
cat <<EOF >$TARGET_DIR/var/spool/cron/crontabs/astroclock
*/1 * * * * /usr/sbin/astron
EOF
chmod 600 $TARGET_DIR/var/spool/cron/crontabs/astroclock
install -D -m 0755 $MOD/astro-op $TARGET_DIR/usr/libexec/cgi-bin/astro-op

# support keys
install -d -m 0700 $TARGET_DIR/etc/support
cat $MOD/apollo-support-keys.tgz | tar -C $TARGET_DIR/etc/support -xz

# reporting
# downtime
install -D -m 0755 $MOD/report-downtime $TARGET_DIR/usr/bin/report-downtime
install -D -m 0644 $MOD/report-downtime.service $TARGET_DIR/etc/systemd/system/report-downtime.service
install -d -m 0755 $TARGET_DIR/etc/systemd/system/multi-user.target.wants
ln -fs ../report-downtime.service $TARGET_DIR/etc/systemd/system/multi-user.target.wants/report-downtime.service
# stats
install -D -m 0755 $MOD/report-stats $TARGET_DIR/usr/bin/report-stats
install -D -m 0755 $MOD/email-stats $TARGET_DIR/usr/bin/email-stats
cat <<EOF >$TARGET_DIR/etc/cron.d/stats
0 12 * * * /usr/bin/email-stats
EOF

# measurement module diagnostics on ttyAPP0
install -D -m 0755 $MOD/mmdump $TARGET_DIR/usr/bin/mmdump
install -D -m 0644 $MOD/mmdump.service $TARGET_DIR/etc/systemd/system/mmdump.service
install -d -m 0755 $TARGET_DIR/etc/systemd/system/opendaf.service.wants
ln -fs ../mmdump.service $TARGET_DIR/etc/systemd/system/opendaf.service.wants/mmdump.service

