#!/bin/sh

set -e

BR=$(pwd)
MOD=$BR/board/tind/compact-rtu/mod-dave

mkdir -p $TARGET_DIR/usr/share/webapps

# function modules
install -D -m 0755 $MOD/controller.exe $TARGET_DIR/usr/share/opendaf/function-modules/controller.exe
cd $TARGET_DIR/var/lib/opendaf/function-modules && ln -sf ../../../../usr/share/opendaf/function-modules/controller.exe controller.exe

# index page

exists() { [[ -f $1 ]]; }

if [ "$BRAND" == "" ]; then
	BRAND=dave
fi

install -d $TARGET_DIR/usr/share/webapps/index/css
install -d $TARGET_DIR/usr/share/webapps/index/img

pushd $MOD/brand/$BRAND
exists *.html && install -m 0644 *.html $TARGET_DIR/usr/share/webapps/index/
exists *.css && install -m 0644 *.css $TARGET_DIR/usr/share/webapps/index/css
exists *.png && install -m 0644 *.png $TARGET_DIR/usr/share/webapps/index/img
exists *.jpg && install -m 0644 *.jpg $TARGET_DIR/usr/share/webapps/index/img
popd

# dave-ui
if [[ -n "$BRAND" && -e $MOD/dave-ui-$BRAND.tgz ]]; then
	tar -C $TARGET_DIR/usr/share/webapps -xf $MOD/dave-ui-$BRAND.tgz
else
	tar -C $TARGET_DIR/usr/share/webapps -xf $MOD/dave-ui.tgz
fi
cd $TARGET_DIR/var/www && ln -sf ../../usr/share/webapps/dave-ui dave-ui

# lighttpd mod-specific conf
install -D -m 0644 $MOD/lighttpd-mod.conf $TARGET_DIR/etc/lighttpd/conf.d/mod.conf

# mod upgrade script
install -D -m 0755 $MOD/mod-upgrade $TARGET_DIR/usr/sbin/mod-upgrade

# support keys
install -d -m 0700 $TARGET_DIR/etc/support
cat $MOD/dave-support-keys.tgz | tar -C $TARGET_DIR/etc/support -xz

