#!/bin/sh

set -e

BR=$(pwd)
MOD=$BR/board/tind/compact-rtu/mod-falcon

mkdir -p $TARGET_DIR/usr/share/webapps

# function modules
install -D -m 0755 $MOD/controller.exe $TARGET_DIR/usr/share/opendaf/function-modules/controller.exe
mkdir -p $TARGET_DIR/var/lib/opendaf/function-modules
ln -sf /usr/share/opendaf/function-modules/controller.exe $TARGET_DIR/var/lib/opendaf/function-modules/controller.exe

# index page
install -D -m 0644 $MOD/index.html $TARGET_DIR/usr/share/webapps/index/index.html
install -D -m 0644 $MOD/style.css $TARGET_DIR/usr/share/webapps/index/css/style.css

# falcon-ui
tar -C $TARGET_DIR/usr/share/webapps -xf $MOD/falcon-ui.tgz
cd $TARGET_DIR/var/www && ln -sf ../../usr/share/webapps/falcon-ui falcon-ui

# lighttpd mod-specific conf
install -D -m 0644 $MOD/lighttpd-mod.conf $TARGET_DIR/etc/lighttpd/conf.d/mod.conf

# dafman database update
install -D -m 0755 $MOD/update-dafman $TARGET_DIR/usr/sbin/update-dafman
install -D -m 0644 $MOD/update-dafman.service $TARGET_DIR/etc/systemd/system/update-dafman.service
mkdir -p $TARGET_DIR/etc/systemd/system/multi-user.target.wants
ln -fs ../update-dafman.service $TARGET_DIR/etc/systemd/system/multi-user.target.wants/update-dafman.service

# mod upgrade script
install -D -m 0755 $MOD/upgrade $TARGET_DIR/usr/sbin/mod-upgrade

# KVDS on external storage
cat <<EOF >$TARGET_DIR/usr/libexec/cgi-bin/kvds-ext
#!/bin/sh

KVDS_ROOT=/srv/kvds exec /usr/bin/kvds cgi
EOF
chmod 755 $TARGET_DIR/usr/libexec/cgi-bin/kvds-ext

# astroclock configuration
cat <<EOF >$TARGET_DIR/etc/astroclock.conf
set -e
LATITUDE=\$(kvds get site.location.latitude)
LONGITUDE=\$(kvds get site.location.longitude)
EOF

# astroclock runtime service
cat <<EOF >$TARGET_DIR/var/spool/cron/crontabs/astroclock
*/1 * * * * /usr/sbin/astron
EOF
chmod 600 $TARGET_DIR/var/spool/cron/crontabs/astroclock

# support keys
install -d -m 0700 $TARGET_DIR/etc/support
cat $MOD/falcon-support-keys.tgz | tar -C $TARGET_DIR/etc/support -xz

