#!/bin/sh

# move selected files from /etc to /var/etc
# to preserve them between firmware upgrades

set -e

# these environment variables are already set:
# BR2_CONFIG
# TARGET_DIR
# STAGING_DIR
# HOST_DIR
# BINARIES_DIR
# BASE_DIR

mkdir -p $TARGET_DIR/var/etc

for fname in hostname hosts; do
	if [ ! -L $TARGET_DIR/var/etc/$fname ]; then
		mv -fv $TARGET_DIR/etc/$fname $TARGET_DIR/var/etc/$fname
		ln -sf ../var/etc/$fname $TARGET_DIR/etc/$fname
	fi
done

