#!/bin/sh

set -e

export FS_ROOT_SIZE_LEBS=465	# 56.3 MB
export FS_VAR_SIZE_LEBS=465		# 56.3 MB

# these environment variables are already set:
# BR2_CONFIG
# TARGET_DIR
# STAGING_DIR
# HOST_DIR
# BINARIES_DIR
# BASE_DIR

export TOPDIR=`pwd`
SCRIPTDIR=$TOPDIR/board/tind/compact-rtu/scripts
IMAGES=$1
export TMPDIR=$IMAGES/tmp-mkvar

rm -rf $TMPDIR
mkdir $TMPDIR
make -f $SCRIPTDIR/pi_mkvar.mk -C $IMAGES 
rm -rf $TMPDIR

