#!/bin/sh

# system-wide upgrade script

set -e

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

RELEASE_PATH=/etc/release
PREV_RELEASE_PATH=/var/state/previous-release
DAFMAN_DB=/var/lib/opendaf/dafman/dafman.sqlite3

PREV_RELEASE=0

[ -e $PREV_RELEASE_PATH ] && PREV_RELEASE=$(cat $PREV_RELEASE_PATH)

if [ "$PREV_RELEASE" -lt 20120209 ]; then
	echo "Upgrading from $PREV_RELEASE to 20120209"
	ln -sf /usr/libexec/cgi-bin /var/www/cgi-bin
	[ -h /var/spool ] && rm -f /var/spool
	mkdir -p /var/spool/cron/crontabs
fi

echo "Upgrade complete"

mkdir -p $(dirname $PREV_RELEASE_PATH)
cp -f $RELEASE_PATH $PREV_RELEASE_PATH

