#!/bin/sh

# system-wide upgrade script

set -e

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

RELEASE_PATH=/etc/release
PREV_RELEASE_PATH=/var/state/previous-release
DAFMAN_DB=/var/lib/opendaf/dafman/dafman.sqlite3

PREV_RELEASE=0

[ -e $PREV_RELEASE_PATH ] && PREV_RELEASE=$(cat $PREV_RELEASE_PATH)
[ -e $RELEASE_PATH ] && RELEASE=$(cat $RELEASE_PATH)

if [ "$PREV_RELEASE" -lt 20150209 ]; then
	echo "Upgrading from $PREV_RELEASE to 20150209"
	ln -sf /usr/libexec/cgi-bin /var/www/cgi-bin
	[ -h /var/spool ] && rm -f /var/spool
	mkdir -p /var/spool/cron/crontabs
fi

if [ "$PREV_RELEASE" -lt 20150225 ]; then
	echo "Upgrading from $PREV_RELEASE to 20150225"
	mkdir -p /var/etc/NetworkManager/dispatcher.d/pre-down.d
	mkdir -p /var/etc/NetworkManager/dispatcher.d/pre-up.d
fi

if [ "$PREV_RELEASE" -lt 20150412 ]; then
	echo "Upgrading from $PREV_RELEASE to 20150412"
	ln -sf /usr/share/webdaf /var/www/webdaf
fi

if [ "$PREV_RELEASE" -lt 20150423 ]; then
	echo "Upgrading from $PREV_RELEASE to 20150423"
	cat <<EOF >/etc/NetworkManager/system-connections/conn_gsm
[connection]
id=conn_gsm
uuid=9c499e7c-f20d-426a-b606-2e0ee25c6427
type=gsm

[gsm]
number=*99#
apn=internet
EOF
	mkdir -p /var/spool/cron/cronstamps
	mkdir -p /var/spool/astron/astrotabs
fi

if [ "$PREV_RELEASE" -lt 20150701 ]; then
	echo "Upgrading from $PREV_RELEASE to 20150701"
	install -D -m 0644 /usr/share/rang/cfg.json /var/lib/rang/cfg.json
fi

if [ "$PREV_RELEASE" -lt 20150708 ]; then
	echo "Upgrading from $PREV_RELEASE to 20150708"
	for lnk in img css fonts js index.html; do
		rm -f /var/www/$lnk
	done
	ln -sf ../../usr/share/webapps/index/ /var/www/index
fi

if [ "$PREV_RELEASE" -ne "$RELEASE" ]; then
	echo "Force-rendering configuration because of release change"
	rang force-render
fi

echo "Upgrade complete"

mkdir -p $(dirname $PREV_RELEASE_PATH)
cp -f $RELEASE_PATH $PREV_RELEASE_PATH

