#!/bin/sh

set -e

RESET=53
POWER=55

cd /sys/class/gpio

for pin in $POWER $RESET; do
	[ -d gpio$pin ] || echo $pin >export
	echo out > gpio$pin/direction
	echo 0 > gpio$pin/value
done

echo 1 >gpio$POWER/value
echo 1 >gpio$RESET/value

usleep 250000

echo 0 >gpio$POWER/value
usleep 100000
echo 0 >gpio$RESET/value

