#!/bin/sh
#
# System-V init script for the rqwb daemon
#

set -e

RQWB=/usr/bin/rqwb

. /etc/profile

if [ -r /etc/default/rqwb ]; then
	. /etc/default/rqwb
fi

case $1 in
  start)
        echo "Starting RQWB ..."
		if [ $RQWB_ENABLED -eq 1]; then
	        start-stop-daemon -m -p /var/run/rqwb.pid -x $RQWB -b -S -- $RQWB_OPTIONS >/dev/null
		fi
        ;;
  stop)
        echo "Stopping RQWB ..."
		if [ $RQWB_ENABLED -eq 1]; then
        	start-stop-daemon -p /var/run/rqwb.pid -K
		fi
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

