#!/bin/sh
#
# System-V init script for the opensmc daemon
#

set -e

OPENSMC=/usr/bin/opensmc

. /etc/profile

case $1 in
  start)
        echo "Starting OpenDAF..."
        start-stop-daemon -m -p /var/run/opensmc.pid -x $OPENSMC -b -S -- -f /etc/opensmc/svc.conf >/dev/null
        ;;
  stop)
        echo "Stopping OpenDAF..."
        start-stop-daemon -p /var/run/opensmc.pid -K
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

