CSR_WIFI_KMOD_VERSION = 5.1.0
CSR_WIFI_KMOD_SOURCE = csr-wifi-kmod-$(CSR_WIFI_KMOD_VERSION).tgz
CSR_WIFI_KMOD_SITE = ftp://merlin.swind.sk/buildroot-packages
CSR_WIFI_KMOD_DEPENDENCIES = linux
CSR_WIFI_KMOD_INSTALL_STAGING = NO
CSR_WIFI_KMOD_INSTALL_TARGET = YES

CSR_WIFI_KMOD_CONFIG = release
CSR_WIFI_KMOD_SDIO_DRIVER = mmc
CSR_WIFI_KMOD_UNIFI_CONFIG = wext_ap

define CSR_WIFI_KMOD_BUILD_CMDS
	$(MAKE) -C $(@D)/csr/os_linux/driver $(LINUX_MAKE_FLAGS) SDIO_DRIVER=$(CSR_WIFI_KMOD_SDIO_DRIVER) SME=$(CSR_WIFI_KMOD_UNIFI_CONFIG) CONFIG=$(CSR_WIFI_KMOD_CONFIG) KDIR=$(LINUX_DIR) all
endef

define CSR_WIFI_KMOD_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D)/csr/os_linux/driver $(LINUX_MAKE_FLAGS) SDIO_DRIVER=$(CSR_WIFI_KMOD_SDIO_DRIVER) SME=$(CSR_WIFI_KMOD_UNIFI_CONFIG) CONFIG=$(CSR_WIFI_KMOD_CONFIG) KDIR=$(LINUX_DIR) DESTDIR=$(TARGET_DIR) install_modules
endef

$(eval $(generic-package))

