#!/bin/sh

mount -a

export HOME=/root

# show bootup logo
echo 0 > /sys/class/graphics/fbcon/cursor_blink
fbv -i -d 1 -c -u /usr/share/lightpanel/logo.png

UPDATE_IMAGE=/target/var/lib/fwupdate/rootfs.ubifs.sign TARGET=/target/rootfs UMOUNT_LIST="/target/var /proc /sys" FALLBACK="busybox init" exec /sbin/fwupdate update-recover

# fallback
echo 1 > /sys/class/leds/error/brightness

exec busybox init

